USE evacina;

ALTER TABLE CIDADAO
    ADD CONSTRAINT pk_ci PRIMARY KEY (cpf_ci);
    
ALTER TABLE FUNCIONARIO 
	ADD CONSTRAINT pk_fu PRIMARY KEY (cod_fu),
    ADD CONSTRAINT fk_ci_fu FOREIGN KEY (cpf_ci_fu) REFERENCES CIDADAO(cpf_ci)
    ON UPDATE CASCADE ON DELETE CASCADE,
    ADD CONSTRAINT cpf_ci_fu_uk UNIQUE (cpf_ci_fu);
    
ALTER TABLE PRODUTOR_VACINAS
	ADD CONSTRAINT pk_pr PRIMARY KEY (cod_pr);
    
ALTER TABLE PATOGENO
	ADD CONSTRAINT pk_pa PRIMARY KEY (cod_pa);

ALTER TABLE VACINA
	ADD CONSTRAINT pk_va PRIMARY KEY (cod_va);
    
ALTER TABLE LOTE
	ADD CONSTRAINT pk_lo PRIMARY KEY (cod_lo, cod_pr_lo),
    ADD CONSTRAINT fk_pr_lo FOREIGN KEY (cod_pr_lo) REFERENCES PRODUTOR_VACINAS(cod_pr)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    ADD CONSTRAINT fk_va_lo FOREIGN KEY (cod_va_lo) REFERENCES VACINA(cod_va)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE POSTO_VACINACAO
	ADD CONSTRAINT pk_po PRIMARY KEY (cod_po),
    ADD CONSTRAINT endereco_po_uk UNIQUE (estado_po, cidade_po, bairro_po, endereco_po);

ALTER TABLE FRASCO
	ADD CONSTRAINT pk_fr PRIMARY KEY (cod_fr, cod_lo_fr),
    ADD CONSTRAINT fk_lo_fr FOREIGN KEY (cod_lo_fr) REFERENCES LOTE(cod_lo)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    ADD CONSTRAINT fk_po_fr FOREIGN KEY (cod_po_fr) REFERENCES POSTO_VACINACAO(cod_po)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE TRABALHA_EM
	ADD CONSTRAINT pk_te PRIMARY KEY (cod_fu_te, cod_po_te),
    ADD CONSTRAINT fk_fu_te FOREIGN KEY (cod_fu_te) REFERENCES FUNCIONARIO(cod_fu)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    ADD CONSTRAINT fk_po_te FOREIGN KEY (cod_po_te) REFERENCES POSTO_VACINACAO(cod_po)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE APLICA
	ADD CONSTRAINT pk_ap PRIMARY KEY(cpf_ci_ap, cod_fu_ap, cod_fr_ap),
    ADD CONSTRAINT fk_ci_ap FOREIGN KEY (cpf_ci_ap) REFERENCES CIDADAO(cpf_ci)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    ADD CONSTRAINT fk_fu_ap FOREIGN KEY (cod_fu_ap) REFERENCES FUNCIONARIO(cod_fu)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    ADD CONSTRAINT fk_fr_ap FOREIGN KEY (cod_fr_ap) REFERENCES FRASCO(cod_fr)
    ON UPDATE CASCADE ON DELETE RESTRICT;
    
ALTER TABLE IMUNIZA_CONTRA
	ADD CONSTRAINT pk_ic PRIMARY KEY (cod_va_ic, cod_pa_ic),
    ADD CONSTRAINT fk_va_ic FOREIGN KEY (cod_va_ic) REFERENCES VACINA(cod_va)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    ADD CONSTRAINT fk_pa_ic FOREIGN KEY (cod_pa_ic) REFERENCES PATOGENO (cod_pa)
    ON UPDATE CASCADE ON DELETE RESTRICT;
